# Generated by Django 2.2.5 on 2019-09-27 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cat_heroi', '0001_initial'),
        ('universo', '0001_initial'),
        ('habilidade', '0001_initial'),
        ('heroi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroi',
            name='heroi_cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='heroi_cat', to='cat_heroi.Categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heroi',
            name='heroi_hab',
            field=models.ManyToManyField(related_name='heroi_hab', to='habilidade.Habilidade'),
        ),
        migrations.AddField(
            model_name='heroi',
            name='heroi_uni',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='heroi_uni', to='universo.Universo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='heroi',
            name='idade',
            field=models.IntegerField(verbose_name='idade'),
        ),
    ]
