# Generated by Django 2.2.5 on 2019-09-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universo',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
