# Generated by Django 2.2.5 on 2019-09-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_heroi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='categoria'),
        ),
    ]
